name: Build (multiplatform)
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2022, macos-14, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Run `packageReleaseDistributionForCurrentOS`
        run: ./gradlew packageReleaseDistributionForCurrentOS
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-compose-notepad ${{ matrix.os }}
          if-no-files-found: error
          path: build/compose/binaries/main-release/*/*
